{
 "title": "Druid / Druid Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Druid Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Druid Exporter",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "<p style=\"text-align:center;\">\n    <img src=\"https://druid.apache.org/img/druid_nav.png\" height=\"60\" width=\"160\">\n</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Druid Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "druid_health_status" }
   ]
  },
  {
   "title": "Total Datasources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(druid_datasource{})" }
   ]
  },
  {
   "title": "Total Segments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(druid_segment_count)" }
   ]
  },
  {
   "title": "Druid Task's Sucess Percentage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"SUCCESS\"}) / count(druid_tasks_duration{}) * 100"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"RUNNING\"}) by (task_status)",
     "legendFormat": "{{task_status}}"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"FAILED\"}) by (task_status)",
     "legendFormat": "{{task_status}}"
    }
   ]
  },
  {
   "title": "Sucess Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"SUCCESS\"}) by (task_status)",
     "legendFormat": "{{task_status}}"
    }
   ]
  },
  {
   "title": "Unloaded Segments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(sum(druid_emitted_metrics{metric_name=\"segment-loadQueue-count\"}))"
    }
   ]
  },
  {
   "title": "Unloaded Segments Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_emitted_metrics{metric_name=\"segment-loadQueue-size\"})"
    }
   ]
  },
  {
   "title": "JVM Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(druid_emitted_metrics{metric_name=\"jvm-mem-used\"}[$__range])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(druid_emitted_metrics{metric_name=\"jvm-pool-used\"}[$__range])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Ingestion Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ingestion Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_emitted_metrics{metric_name=\"ingest-events-processed\"}[$__range])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ingestion Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_emitted_metrics{metric_name=\"ingest-kafka-lag\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Druid Datasource Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Datasource Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(druid_segment_size)" }
   ]
  },
  {
   "title": "Datasource Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_segment_size{}[$__range])) by (datasource_name)",
     "legendFormat": "{{datasource_name}}"
    }
   ]
  },
  {
   "title": "Replicated Data Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_segment_replicated_size)"
    }
   ]
  },
  {
   "title": "Deep Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(druid_segment_size / 1e+12) * 100"
    }
   ]
  },
  {
   "title": "Datasource  Replication Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(druid_segment_replicated_size) by (datasource_name)",
     "legendFormat": "{{datasource_name}}"
    }
   ]
  },
  {
   "title": "Druid Task Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Druid Task Status",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(druid_tasks_duration) by (datasource, task_id, task_status)"
    }
   ]
  }
 ]
}