---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-exporter
  namespace: druid
spec:
  selector:
    matchLabels:
      druid: metrics
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        druid: metrics
    spec:
      containers:
      - env:
        - name: DRUID_URL
          value: "https://druid-iuneradruid-router:9088"
        - name: INSECURE_TLS_VERIFY
          value: "true"
        - name: LOG_LEVEL
          value: "info"
        - name: DRUID_USER
          valueFrom:
            secretKeyRef:
              name: iuneradruid-auth-secrets
              key: internalUser
        - name: DRUID_PASSWORD
          valueFrom:
            secretKeyRef:
              name: iuneradruid-auth-secrets
              key: internalClientPassword
        # image: iunera/druid-exporter:v0.12.6
        image: iunera/druid-exporter:v0.12.7-3
        imagePullPolicy: Always
        name: druid-exporter
        ports:
        - containerPort: 8080
          protocol: TCP

        resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
          requests:
            memory: "16Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    druid: metrics
  name: druid-exporter
  namespace: druid
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    druid: metrics
  type: ClusterIP
